# Generated by Django 6.0.3 on 2026-10-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occasion', models.CharField(choices=[('corporate', 'Corporate Gifting'), ('festive', 'Festive Gifting'), ('wedding', 'Wedding / Return Gifts'), ('party', 'Party / Event'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'bulk inquiries',
            },
        ),
    ]
